#!/usr/bin/env bash
#transfers a file from our client to a server
#args [local file path] [remote ip] [username] [ssh key path]

if [[ ! $4 ]] ; then
echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
exit
fi

dest_path="~/"
file_path=$1 
ip=$2
user=$3
key_path=$4

scp -i $key_path $file_path $user@$ip:$dest_path
