#!/usr/bin/env bash
#installs nginx and replaces index page to one containing only 'Hello world	'

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx restart
echo 'Hello World' | sudo tee /var/www/html/index.nginx-debian.html
