#!/usr/bin/env bash
#installs nginx and replaces index page to one containing only 'Hello world	'

sudo apt-get update
sudo apt-get install nginx
sudo service nginx restart
echo 'Hello World' | sudo tee /usr/share/nginx/html/index.html
