#!/usr/bin/env bash
#adds a redirection in the nginx/sites-available/default file
#installs nginx and sets up nginx (task 1-install_nginx_webi_server)
#sets 404 and a custom redirection (tasks 3, 4)

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World' | sudo tee /var/www/html/index.nginx-debian.html

file='/etc/nginx/sites-available/default'

# delete redirection line if exists
sudo sed -i '/^rewrite.*www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;$'/d $file
# add redirection rule
sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' $file

# Configure your Nginx server to have a custom 404 (Only run once, not idemp.)
sudo mkdir -p  /var/www/html/
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error-page.html
sudo sed -i '/server_name _;/a error_page 404 \/error-page.html;' $file
sudo service nginx restart
