#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header:
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

# nginx config file
file='/etc/nginx/sites-available/default'
nginx_host=$(hostname)

# add redirection rule
sudo sed -i "/server_name _;/a X-Served-By "$nginx_host"" "$file"
