#!/usr/bin/env bash
# installs HAProxy and configures as a load balancer

sudo apt-get update -y
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get install -y haproxy=2.0.\*

file='/etc/haproxy/haproxy.cfg'

# copy file to backup config
sudo cp "$file" "$file".back

# enable proxy
sudo sed -i "s/ENABLED=0/ENABLED=1/" "/etc/default/haproxy"

# add load balancer 
echo -e "listen http-incoming\n\tmode http\n\tbalance roundrobin\n\tbind :80\n\toption forwardfor\n\tserver 4441-web-01 3.80.136.213 check\n\tserver 4441-web-02 54.205.179.111 check" | sudo tee -a "$file"

# restart
sudo service haproxy restart
