#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header:
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World' | sudo tee /var/www/html/index.nginx-debian.html

file='/etc/nginx/sites-available/default'

# delete redirection line if exists
sudo sed -i '/^rewrite.*www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;$'/d $file
# add redirection rule
sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' $file

# Configure your Nginx server to have a custom 404 (Only run once, not idemp.)
sudo mkdir -p  /var/www/html/
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error-page.html
sudo sed -i '/server_name _;/a error_page 404 \/error-page.html;' $file
sudo service nginx restart

nginx_host=$(hostname)

# add load balancer redirection
sudo sed -i "/server_name _;/a X-Served-By '$nginx_host'" "$file"

