#!/usr/bin/env bash
file='/etc/nginx/nginx.conf'
#file='nginx.conf'
cp "$file" "$file".back
chmod 777 "$file"
sudo sed -ri 's/#?user www-data;/user nginx;/' "$file"
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx 'service nginx restart'
